### ISSUE TITLE
Fix Sound Bugs.

### ISSUE THREAD

**Issue by MC1865** [1865-Mods/SMEE#15]
MCreator keeps putting unnecessary changes and make all of my sounds (what's supposed to sound) to something else. Until Mcreator fixes this stubborn bug I have to deal with it, for now.
- [x] Fix ALL Sounds
- [x] Recover all affixes in certain procedures
- [x] Remove already used sound presets.

**Comment by ghost** [comment]
All Sound Problems is fixed, since version 4.5.
